name = "gentle-shape-f6d4"
main = "./src/index.py"
compatibility_flags = ["python_workers"]
compatibility_date = "2024-12-30"


[env.production]
name = "production-site"
route = "https://production-site.infsite.org/"
vars = { API_HOST = "https://infsite.org/?prod" }

[env.staging]
name = "staging-site"
route = "https://staging-site.infsite.org/"
vars = { API_HOST = "https://infsite.org/?staging" }

[env.dev]
name = "dev-site"
route = "https://dev-site.infsite.org/"
vars = { API_HOST = "https://infsite.org/?dev" }