name: Build and Deploy Python Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "requirements.txt"
      
      - name: Generate artifacts to test
        run: mkdir dist && rsync -aP . dist/

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        name: Download Build Artifacts
        with:
          name: build-artifacts
          path: dist/
      
      - name: Retrive artifacts
        run: ls -ls dist/

      - name: Deploy to Cloudflare Workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          cd dist
          npm install -g wrangler
          wrangler deploy --env production